import pandas as pd
import numpy as np
from src.utils.logger import get_logger
from src.utils.config_loader import load_config

logger = get_logger("indicators")
config = load_config()

def calculate_rsi(series: pd.Series, period: int) -> pd.Series:
    delta = series.diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
    rs = gain / loss
    return 100 - (100 / (1 + rs))

def calculate_sma(series: pd.Series, period: int) -> pd.Series:
    return series.rolling(window=period).mean()

def calculate_ema(series: pd.Series, period: int) -> pd.Series:
    return series.ewm(span=period, adjust=False).mean()

def calculate_macd(df: pd.DataFrame, fast: int, slow: int, signal: int) -> pd.DataFrame:
    ema_fast = calculate_ema(df['close'], fast)
    ema_slow = calculate_ema(df['close'], slow)
    macd_line = ema_fast - ema_slow
    signal_line = calculate_ema(macd_line, signal)
    histogram = macd_line - signal_line
    return pd.DataFrame({'MACD': macd_line, 'Signal': signal_line, 'Hist': histogram})

def calculate_bollinger_bands(df: pd.DataFrame, period: int, std_dev: float) -> pd.DataFrame:
    sma = calculate_sma(df['close'], period)
    std = df['close'].rolling(window=period).std()
    upper = sma + (std * std_dev)
    lower = sma - (std * std_dev)
    return pd.DataFrame({'BB_Upper': upper, 'BB_Middle': sma, 'BB_Lower': lower})

def add_technical_indicators(df: pd.DataFrame) -> pd.DataFrame:
    """
    Main wrapper function to add all configured indicators to the DataFrame.
    """
    if df.empty:
        return df

    try:
        # Load config settings
        ind_cfg = config.get('indicators', {})
        
        # RSI
        df['RSI'] = calculate_rsi(df['close'], ind_cfg.get('rsi_period', 14))
        
        # Moving Averages
        df['SMA_20'] = calculate_sma(df['close'], ind_cfg.get('sma_short', 20))
        df['SMA_50'] = calculate_sma(df['close'], ind_cfg.get('sma_long', 50))
        df['EMA_20'] = calculate_ema(df['close'], ind_cfg.get('ema_period', 20))
        
        # MACD
        macd_df = calculate_macd(df, 12, 26, 9)
        df = pd.concat([df, macd_df], axis=1)
        
        # Bollinger Bands
        bb_df = calculate_bollinger_bands(df, ind_cfg.get('bollinger_period', 20), ind_cfg.get('bollinger_std', 2.0))
        df = pd.concat([df, bb_df], axis=1)
        
        # Drop NaN values generated by rolling windows
        df.dropna(inplace=True)
        
        logger.info(f"Indicators calculated. Rows remaining: {len(df)}")
        return df
    
    except Exception as e:
        logger.error(f"Error calculating indicators: {e}")
        return df